import React from "react";
import { motion } from "framer-motion";
import { Bot, User, Copy, Check } from "lucide-react";
import { LiveError, LivePreview, LiveProvider } from "react-live";
import CodeBlock from "../../layouts/docs/components/CodeBlock";
import ReactPageBlock from "../../layouts/docs/components/ReactPageBlock";
import CodePreviewPage from "../../layouts/docs/components/CodePreviewBlock";

const BotCodeResult = ({
  title,
  message,
  code,
  language = "jsx",
  rawResponse,
}) => (
  <div className="w-full mt-3 space-y-4">
    <ReactPageBlock
      title={title || "Generated UI"}
      description={message || "Preview + code generated by Neuctra UI Bot."}
      language={language}
      showCode={true}
      showPreview={true}
      livePreview={true}
      height="420px"
      code={code}
      preview={
        <LiveProvider code={code} noInline={false}>
          <div className="space-y-3">
            <LiveError className="text-rose-300 text-sm p-3 bg-rose-950/60 rounded-lg border border-rose-700/30" />
            <div className="rounded-lg border border-zinc-700 bg-zinc-900/70 p-4">
              <LivePreview className="w-full" />
            </div>
          </div>
        </LiveProvider>
      }
    />

    <CodePreviewPage
      compact={true}
      title="AI Generated Output"
      description="Structured code view for copy and implementation."
      code={code}
      preview={
        <LiveProvider code={code} noInline={false}>
          <LiveError className="text-rose-300 text-sm p-3 bg-rose-950/60 rounded-lg border border-rose-700/30 mb-3" />
          <LivePreview className="rounded-lg border border-zinc-700 bg-zinc-900/70 p-4" />
        </LiveProvider>
      }
    />

    <CodeBlock
      tabs={[
        { name: "JSX", code: code || "// No code generated", language: "jsx" },
        {
          name: "Raw Response",
          code: rawResponse || "// No raw response",
          language: "json",
        },
      ]}
      showLineNumbers={true}
    />
  </div>
);

const ChatMessage = ({ message, isUser, isStreaming = false }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = async () => {
    const textToCopy = message.code || message.text;
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  return (
    <motion.div
      className={`flex w-full mb-6 ${isUser ? "justify-end" : "justify-start"}`}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
    >
      <div
        className={`flex gap-4 max-w-[85%] ${isUser ? "flex-row-reverse" : "flex-row"}`}
      >
        {/* Avatar */}
        <div
          className={`flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center shadow-lg ${
            isUser
              ? "bg-primary text-white"
              : "bg-gradient-to-br from-primary to-emerald-500 text-white"
          }`}
        >
          {isUser ? <User size={20} /> : <Bot size={20} />}
        </div>

        {/* Message Content */}
        <div
          className={`flex flex-col ${isUser ? "items-end" : "items-start"} w-full space-y-3`}
        >
          {/* Message Bubble */}
          <div
            className={`relative group px-5 py-3.5 rounded-2xl shadow-sm ${
              isUser
                ? "bg-primary text-white rounded-tr-sm"
                : "bg-zinc-900/80 text-zinc-100 rounded-tl-sm border border-zinc-800"
            }`}
          >
            {/* Streaming cursor */}
            {isStreaming && !isUser && (
              <motion.span
                className="inline-block w-2 h-5 bg-primary ml-1"
                animate={{ opacity: [1, 0] }}
                transition={{ duration: 0.8, repeat: Infinity }}
              />
            )}

            {/* Message Text */}
            <p className="leading-relaxed whitespace-pre-wrap text-[15px]">
              {message.text}
            </p>

            {/* Error Message */}
            {!!message.error && (
              <p className="mt-2 text-sm text-rose-400">{message.error}</p>
            )}

            {/* Copy Button */}
            {!isUser && (message.text || message.code) && (
              <button
                onClick={handleCopy}
                className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity p-1.5 rounded-lg bg-zinc-800/50 hover:bg-zinc-700/50 text-zinc-400 hover:text-zinc-200"
                title="Copy message"
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
              </button>
            )}
          </div>

          {/* Code Results for Bot Messages */}
          {!isUser && message.code && !isStreaming && (
            <BotCodeResult
              title={message.title}
              message={message.text}
              code={message.code}
              language={message.language}
              rawResponse={message.rawResponse}
            />
          )}

          {/* Timestamp */}
          <div className={`text-xs text-zinc-500 ${isUser ? 'text-right' : 'text-left'}`}>
            {message.timestamp && new Date(message.timestamp).toLocaleTimeString([], {
              hour: '2-digit',
              minute: '2-digit'
            })}
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default ChatMessage;
