export function buildDesignRulesPrompt() {
  return [
    "Design system rules:",
    "",
    "LAYOUT:",
    "- Use modern SaaS layouts.",
    "- Use large, impactful hero sections.",
    "- Wrap major sections in Container.",
    "- Maintain generous whitespace.",
    "- Use consistent spacing scale.",
    "- Prefer grid and flex layouts.",
    "- Ensure fully responsive design.",
    "- Create clear content flow between sections.",
    "",
    "VISUAL HIERARCHY:",
    "- Strong typography hierarchy.",
    "- Large headlines with concise supporting text.",
    "- Clear CTA visibility.",
    "- Important content must stand out immediately.",
    "- Use spacing before adding visual complexity.",
    "",
    "AESTHETICS:",
    "- Modern and premium appearance.",
    "- Clean visual balance.",
    "- Subtle shadows only when necessary.",
    "- Soft rounded corners.",
    "- Professional SaaS design language.",
    "- Elegant card layouts.",
    "- Consistent visual rhythm.",
    "- Avoid clutter.",
    "",
    "COLORS:",
    "- ONLY use approved Neuctra theme tokens.",
    "- Never use Tailwind colors (blue-500, red-500, gray-200, etc).",
    "- Never use Tailwind classes of blur.",
    "- Never use hex colors.",
    "- Never use rgb() or hsl() values.",
    "- Use bg-primary for primary actions.",
    "- Use bg-background for page backgrounds.",
    "- Use text-foreground for primary text.",
    "- Use text-accent-foreground for secondary text.",
    "- Use bg-accent for secondary surfaces.",
    "- Use border-border for all borders.",
    "- Use text-destructive for destructive states.",
    "",
    "COMPONENTS:",
    "- Use Neuctra UI components whenever possible.",
    "- Enhance components using className only.",
    "- Build production-ready interfaces.",
    "- Prefer reusable patterns.",
    "- Ensure accessibility and readability.",
    "",
    "OUTPUT:",
    "- Generate complete sections, not wireframes.",
    "- Create polished, production-quality UI.",
    "- Focus on conversion-oriented SaaS experiences.",
    "- Make the UI feel modern, premium, and aesthetically refined.",
  ].join("\\n");
}
